// <auto-generated />
using BarbecueChallengeDotNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarbecueChallengeDotNet.Migrations
{
    [DbContext(typeof(ParticipantContext))]
    [Migration("20201112195623_BancoInicial")]
    partial class BancoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BarbecueChallengeDotNet.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<bool>("SeCancelado");

                    b.Property<bool>("SeConvidado");

                    b.Property<bool>("SeEmpregado");

                    b.Property<bool>("SeVaiBeber");

                    b.HasKey("Id");

                    b.ToTable("Participant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Teste 1",
                            SeCancelado = false,
                            SeConvidado = true,
                            SeEmpregado = false,
                            SeVaiBeber = true
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Teste 2",
                            SeCancelado = true,
                            SeConvidado = false,
                            SeEmpregado = true,
                            SeVaiBeber = false
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Teste 3",
                            SeCancelado = true,
                            SeConvidado = true,
                            SeEmpregado = false,
                            SeVaiBeber = false
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Teste 4",
                            SeCancelado = true,
                            SeConvidado = true,
                            SeEmpregado = false,
                            SeVaiBeber = true
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Teste 5",
                            SeCancelado = false,
                            SeConvidado = false,
                            SeEmpregado = true,
                            SeVaiBeber = true
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Teste 6",
                            SeCancelado = true,
                            SeConvidado = false,
                            SeEmpregado = true,
                            SeVaiBeber = true
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Teste 7",
                            SeCancelado = true,
                            SeConvidado = false,
                            SeEmpregado = true,
                            SeVaiBeber = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
